### PR TITLE
added typescript types

### LINKED ISSUE #2: Typescript support?
Would love to see types added for this. 👍

### PR DESCRIPTION
**Pull request by ImLunaHey**
Closes #2 

I think `types` also needs to be updated in `package.json`

### CODE REVIEW

**Comment by ImLunaHey** [comment]
Just noticed this is missing the events typed for the `on` and `off` methods for the event emitter. I can fix these if you want this to be merged. If not I'll close it and wait for `v3.0.0`.

**Comment by kartikk221** [comment]
I've closed this pull request for now, so feel free to make your changes in your fork. I'd be more than glad to merge a PR after 3.0.0 is out as conflicts/changes will be clearer.

**Comment by ImLunaHey** [comment]
Do you have an ETA on `3.0.0` I noticed there's no branch for it?

**Comment by kartikk221** [comment]
I'm only in the planning stages for it right now and the breaking changes will mostly be that LiveDirectory will receive the ability to fine tune things such as which files are cached in memory/which files are streamed from disk along with other dependent properties such as etags etc. I would say that the ETA is 1 - 2 weeks.

**Pull request closed without merging**
